### ISSUE TITLE
Could we add the "Activities" to the main RailsBridge docs?

### ISSUE THREAD

**Issue by lilliealbert** [RailsBridge-CapeTown/rails-bridge-capetown.github.com#35]
hey y'all!

I think this page is completely amazing: https://railsbridgecapetown.org/activities.html#whatyouknowandwhatsyourplan

I don't know who wrote it, I'm guessing @SteveBarnett? 

Would someone be interested in adding it as a page to the main RailsBridge docs, maybe under "Other" called "Classroom Activities"? (Or if you're busy, I could do it, and link back to the original for credit at the bottom of the page.)

We could then link to it from the beginning of various curriculums and encourage teachers to use it throughout their classes and everything could be more awesome for everyone!

**Comment by SteveBarnett** [comment]
Woo, thank you! :smile:  :tada:

I had a hand in it, yes, but the main credit goes to [Sharon Bowman](http://bowperson.com/) and her awesome books. I've just added a credit at the top of [the activities page](https://railsbridgecapetown.org/activities.html) (and here's [a short post I did of the thinking / motivation behind it](https://naga.co.za/2015/04/06/training-from-the-back-of-the-room/) in case you're interested.).

I would be **super happy** to get these activity thingies into the main docs because I think they improve the overall learning experience of a RailsBridge workshop. I'm unlikely to be able to work on this for at least a week, I'm afraid, but:
1. I am happy for someone else to (as long as the credit to Bowman remains);
2. I will post this in our RailsBridge ZA Slack and see if anyone there is keen / available, and ask them to chime in here.

Yay! :smile_cat:

**Comment by SteveBarnett** [comment]
@lilliealbert Sorry for the delay! But a PR is there now \o/.

**Comment by SteveBarnett** [comment]
@lilliealbert Done! https://github.com/railsbridge/docs/pull/529 \o/

**Comment by lilliealbert** [comment]
woooo!
